# Protein-defect interactions

In [2]:
import sys, os
project_root = os.path.abspath("..")
if project_root not in sys.path:
    sys.path.insert(0, project_root)

import importlib
import packing_defect.core.interactions as inter
importlib.reload(inter)

In [3]:

dirs = ["results_defect/PLacyl", "results_defect/TGacyl", "results_defect/TGglyc"]
df = inter.run(dirs, cutoff=2.0, output_csv="combined_interactions.csv")
df.head()

Processing PLacyl frame PLacyl_frame_0.gro
Processing PLacyl frame PLacyl_frame_1.gro
Processing PLacyl frame PLacyl_frame_2.gro
Processing PLacyl frame PLacyl_frame_3.gro
Processing PLacyl frame PLacyl_frame_4.gro
Processing PLacyl frame PLacyl_frame_5.gro
Processing PLacyl frame PLacyl_frame_6.gro
Processing PLacyl frame PLacyl_frame_7.gro
Processing PLacyl frame PLacyl_frame_8.gro
Processing PLacyl frame PLacyl_frame_9.gro
Processing TGacyl frame TGacyl_frame_0.gro
Processing TGacyl frame TGacyl_frame_1.gro
Processing TGacyl frame TGacyl_frame_2.gro
Processing TGacyl frame TGacyl_frame_3.gro
Processing TGacyl frame TGacyl_frame_4.gro
Processing TGacyl frame TGacyl_frame_5.gro
Processing TGacyl frame TGacyl_frame_6.gro
Processing TGacyl frame TGacyl_frame_7.gro
Processing TGacyl frame TGacyl_frame_8.gro
Processing TGacyl frame TGacyl_frame_9.gro
Processing TGglyc frame TGglyc_frame_0.gro
Processing TGglyc frame TGglyc_frame_1.gro
Processing TGglyc frame TGglyc_frame_2.gro
Processing TGglyc frame TGglyc_frame_3.gro
Processing TGglyc frame TGglyc_frame_4.gro
Processing TGglyc frame TGglyc_frame_5.gro
Processing TGglyc frame TGglyc_frame_6.gro
Processing TGglyc frame TGglyc_frame_7.gro
Processing TGglyc frame TGglyc_frame_8.gro
Processing TGglyc frame TGglyc_frame_9.gro
Combined CSV written to combined_interactions.csv

     type  frame  resid resname
0  PLacyl      0     21     LEU
1  PLacyl      0     22     ARG
2  PLacyl      3      1     PHE
3  PLacyl      4      1     PHE
4  PLacyl      5      2     GLN

In [4]:
df

      type  frame  resid resname
0   PLacyl      0     21     LEU
1   PLacyl      0     22     ARG
2   PLacyl      3      1     PHE
3   PLacyl      4      1     PHE
4   PLacyl      5      2     GLN
5   PLacyl      6      1     PHE
6   PLacyl      8      1     PHE
7   PLacyl      8      2     GLN
8   PLacyl      9      1     PHE
9   PLacyl      9     21     LEU
10  PLacyl      9     22     ARG
11  PLacyl      9     25     VAL
12  TGacyl      0     18     PRO
13  TGacyl      0     21     LEU